#pragma once

#include <boost/outcome.hpp>

namespace lily::core
{
    enum class ErrorCode : uint8_t
    {
        LILY_ERRORCODE_SUCCESS,   // No error
        LILY_ERRORCODE_EXPECTED,  // Expected error, refer to the message generated by the function for the detail
        LILY_ERRORCODE_UNEXPECTED // Unexpected error that occurs without the error detail
    };

    static constexpr auto success = boost::outcome_v2::success();

    template<typename T>
    using Expect = boost::outcome_v2::basic_result<T, ErrorCode,
                                                   boost::outcome_v2::policy::throw_bad_result_access<ErrorCode, void>>;
} // namespace lily::core
